Updated to latest mapstore
geosolutions-it/austrocontrol-C125 pull request #214
Opened 2020-10-01 14:41 UTC by offtherailz

add all the configurations and enabled geostory, aligned all the plugins

2020-10-01 15:40 UTC, MV88 requested changes
i think is good, but pluginsConfig.json should be in the root?

2020-10-01 15:40 UTC, MV88 commented on js/pluginsConfig.json
> +{
should this be on the root instead?

2020-10-01 15:47 UTC, offtherailz commented on js/pluginsConfig.json
> +{
yes, I think I moved it accitendally. Thank you

2020-10-02 07:53 UTC, MV88 approved these changes

2020-10-02 08:07 UTC, merged